### ISSUE TITLE
push方法耦合有点高？很多人并不愿意使用这类的非原生方法名的库。

### ISSUE THREAD

**Issue by jinxiansen** [alanwangmodify/WXSTransition#1]
因为push pop方法实在太多，跳转和返回如果一个个替换该多麻烦，而且不想用这个库的时候一个个改还是问题。
所以楼主的方法如果能替换系统的就好一些了。

**Comment by alanwangmodify** [comment]
我一开始就是hook 原生 push 和 present的方法，实现调用原生方法就可以直接调用动画，但是实际使用的时候发现了两个问题：1、如果头文件加在pch文件中，所有的原生push、present都变成我的库的效果，2、需要多一行代码来选择动画类型，耦合度也一样。
后面思考了很久参照SDWebImage这种加前缀的调用方法区分开来。

如果你工程中的调整都用到同一个动画，可以用Method Sizzing 交换原生的跳转方法。
