### ISSUE TITLE
pod search WXSTransition

### ISSUE THREAD

**Issue by zdiovo** [alanwangmodify/WXSTransition#12]
$ pod search WXSTransition
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:141: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
Creating search index for spec repo 'master'.. Done!
[!] Unable to find a pod with name, author, summary, or description matching `WXSTransition`

**Comment by alanwangmodify** [comment]
一些配置出了一些问题，现在还不支持cocoapod
