### ISSUE TITLE
- (void)wxs_pushViewController:(UIViewController *)viewController makeTransition:(WXSTransitionBlock) transitionBlock 

### ISSUE THREAD

**Issue by angBiu** [alanwangmodify/WXSTransition#14]
这个方法 有些会导致内存泄露。。。 比如transition.animationType = WXSTransitionAnimationTypeSysFade;  下一个界面的delloc不走了

**Comment by angBiu** [comment]
WXSTransitionAnimationTypeViewMoveToNextVC 比如这个。。。 第一次push 过去 delloc 不走  第二次才会走 demo 也这样。。。

**Comment by alanwangmodify** [comment]
前段时间进行了一次代码结构优化，由于之前是没问题的，所以忽略了，我会尽快解决泄漏问题
