### ISSUE TITLE
能不能提供个方法修改返回那个view？

### ISSUE THREAD

**Issue by joshua-hua** [alanwangmodify/WXSTransition#18]
你好，因为我跳转到图片浏览器，会改变imgview的位置，能否提供个返回的时候修改
@property (nonatomic, strong) UIView     *targetView;

的方法呢？

**Comment by alanwangmodify** [comment]
确实之前没有考虑到返回的灵活定制，但是要加上这个返回的灵活定制的话，涉及到的地方比较多，所以暂时应该没时间加上。
