### ISSUE TITLE
push WXSTransitionAnimationTypePointSpreadPresent 类型的动画的时候，tabbar 问题

### ISSUE THREAD

**Issue by light-bo** [alanwangmodify/WXSTransition#19]
使用 **WXSTransitionAnimationTypePointSpreadPresent** 方式从 A  push 到 B viewController，但是，由于 A 底部有 tabbar，在 push 过去的时候底部 tabbar 会有系统动画，很影响动画的效果，大神，怎么取消 tabbar 的动画呢？ ^_^ @alanwangmodify

**Comment by 13298897828** [comment]
问下解决了吗,同样的问题,不能解决根本没法用

**Comment by alanwangmodify** [comment]
push之前把tabBar隐藏
    self.tabBarController.tabBar.hidden = YES;
pop后在viewDidApear里显示
    self.tabBarController.tabBar.hidden = NO;

**Comment by 13298897828** [comment]
试过这个办法,不能解决根本问题,pop一半之后再回去的话,就会是显示状态.我先用了设置window为白色,看着和正常的pop效果相似.没想到更好的办法

**Comment by alanwangmodify** [comment]
你是不是设置了 self.hidesBottomBarWhenPushed = YES ？
把这个去掉，用我刚才说的那样，手动控制tabbar的隐藏和显示时机
