### ISSUE TITLE
viewMove动画

### ISSUE THREAD

**Issue by cleven1** [alanwangmodify/WXSTransition#20]
viewMove过程中图片不显示,显示白色,这样就失去了viewMove的效果,请修改一下

**Comment by alanwangmodify** [comment]
不好意思，我没理解你描述的这个清楚，
你是说，使用viewmove这个动画的时候,你自己吧图片hidden了，还是这个动画出bug了，在动画过程中不显示了。

**Comment by cleven1** [comment]
是在动画过程中不显示  你可以运行一下你的项目看一下 在动画过程中显示一片白色
