### ISSUE TITLE
不能左滑

### ISSUE THREAD

**Issue by lihuichina** [alanwangmodify/WXSTransition#21]
转场场动画后 该页面的tableview cell 调用UITableViewRowAction左滑方法时  不能左滑 ，变成了刷新，请解决

**Comment by alanwangmodify** [comment]
应该是手势冲突了，你试一下调用的时候设置
transition.backGestureEnable = NO
但是这样就不能通过侧滑返回了

**Comment by lihuichina** [comment]
你好，还有个小问题，你这边翻转动画时，背景是黑色的，能不能设置别的颜色比如白色

**Comment by alanwangmodify** [comment]
请问是哪一个翻转动画，WXSTransitionAnimationTypeSysOglFlip那四个吗？这四个是私有API的动画。

**Comment by lihuichina** [comment]
对 ，私有的话就不能通过审核呀，另外    WXSTransitionAnimationTypeBrickOpenVertical和
    WXSTransitionAnimationTypeBrickOpenHorizontal,转场返回的时候，页面变模糊了 ，WXSTransitionAnimationTypeBrickOpenHorizontal还没有完全合上，中间有一条缝隙

**Comment by alanwangmodify** [comment]
这些API可以安全使用，类似tubey这些有风险的API里面都没有用你可以看一下这篇文章
http://www.lidaren.com/archives/733

BrickOpen是渲染成一张图片，没有用snaptview方法，看起来会模糊一些，比较像砖块效果

**Comment by alanwangmodify** [comment]
WXSTransitionAnimationTypeBrickOpenHorizontal 的bug修复了
