### ISSUE TITLE
A使用转场动画Push到B，B在普通push到C，这时候延续了A到B的自定义动画，如何取消这个？

### ISSUE THREAD

**Issue by luffySaw** [alanwangmodify/WXSTransition#22]
[self.navigationController wxs_pushViewController:scoreSearchVC makeTransition:^(WXSTransitionProperty *transition) {
        transition.animationType = WXSTransitionAnimationTypeSysFade;
        transition.animationTime = 0.25;
        transition.backGestureEnable = NO;
    }];
如代码，Apush到B使用了WXSTransitionAnimationTypeSysFade，但是在B页面有进行普通的push到C，然后依然延续了WXSTransitionAnimationTypeSysFade的效果，从C回来之后再尽心push就正常了，就是只有第一次出问题。这个如何解决？？

**Comment by alanwangmodify** [comment]
谢谢的你issue,我找到原因了，是我在push完之后的delegate依然还在的缘故，我已经修复这个问题。
你可以在
 [self.navigationController pushViewController:VC animated:YES];
之前加上：
self.navigationController.delegate = nil;
或者下载我修复后的WXSTransiton.
