### ISSUE TITLE
ViewMove 动画

### ISSUE THREAD

**Issue by xiny123** [alanwangmodify/WXSTransition#23]
如果是 push Viewcontroller的话    下个 vc 做动画的 view（ transition.targetView）会从（0，0）开始布局。

如果全局统一设置  self.edgesForExtendedLayout = UIRectEdgeNone; 做动画的transition.targetView 先为(0,0)，动画结束之后又变为(0,64),有一顿的感觉。

如过在''- (void)viewDidLayoutSubviews 设置transition.targetView 为(0,0)，没有一顿的情况了，但是返回的时候，会从（假如之前是（0,64）先恢复到（0,0）然后再做动画。

这种情况移除导航条就没问题，不知道有导航条的情况下怎么解决

**Comment by alanwangmodify** [comment]
你好，不知道能不能提供一下代码，我没能完全理解你描述的情况。

**Comment by YanweiLi** [comment]
@xiny123 我也遇到了这样的情况。 xiny的意思是：
ViewController navigationController.navigationBar.translucent = NO 的情况下面，ViewController的view 布局应该是从Window的（0，64）开始。

但是使用wxs库后，push ViewController，VC的view布局先从（0，0）开始，然后跳转到(0，64)。

我看了一下wxs代码库，没有找到原因。

希望作者解决一下。
