### ISSUE TITLE
跳转带有xib的控制器适配出错

### ISSUE THREAD

**Issue by hanjunqiang** [alanwangmodify/WXSTransition#25]
跳转带有xib的控制器，模拟器的Size选择free,转场后view的大小就是xib的大小，而不是自适应当前手机屏幕。

**Comment by luffySaw** [comment]
我也有这个问题，请问有啥方法？

**Comment by alanwangmodify** [comment]
目前没有兼容Xib和stroryboard的情况，现在暂时没有解决方法。

**Comment by hanjunqiang** [comment]
@alanwangmodify 嗯，希望以后会支持
