### ISSUE TITLE
麻烦问下含有method_exchangeImplementations 还能用吗？

### ISSUE THREAD

**Issue by lbwnh123** [alanwangmodify/WXSTransition#26]
+(void)load {
    
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        
        Method method0 = class_getInstanceMethod(self.class, @selector(popViewControllerAnimated:));
        Method method1 = class_getInstanceMethod(self.class, @selector(wxs_popViewControllerAnimated:));
        method_exchangeImplementations(method0, method1);
        
    });
}

**Comment by alanwangmodify** [comment]
可以用的，JSPatch 是因为使用了下发脚本，runtime相关方法是没有关系的。
