### ISSUE TITLE
不支持xib吗?

### ISSUE THREAD

**Issue by 321zhangyang** [alanwangmodify/WXSTransition#3]
跳转到xib写的界面 会出现问题

**Comment by alanwangmodify** [comment]
不支持storyBoard拖拽跳转。跳转到xib写的界面我自己测试了一下，没问题的。
可以贴一下代码和上传一下xib吗

**Comment by 321zhangyang** [comment]
[self wxs_presentViewController:[[testViewController alloc] init] animationType:WXSTransitionAnimationTypePageTransition + indexPath.row completion:nil]; 
我在xib中直接拖了一个button 就这样跳过去了 我用的6模拟器 如果xibsize不选4.7的话 这个button 就会移动位置 方便的话 能不能加我下qq 这上面 我感觉说不明白 842810148

**Comment by alanwangmodify** [comment]
你是简书评论的那一位吗？我收到邮件了，目前其实还没有专门对xib进行支持，之后有时间的话会研究一下xib还有storyboard的情况的，现在先只适用于纯代码中。
