### ISSUE TITLE
建议增加属性控制是否开启UIPanGestureRecognizer手势

### ISSUE THREAD

**Issue by wanshanhu79** [alanwangmodify/WXSTransition#4]
项目中引用了“## UINavigationController+FDFullscreenPopGesture”，一个全局滑动返回扩展。
再引用你的转场动画后，发现全局滑动返回功能无法作用，并且有时出现奇怪的问题，页面有数据但现实白色，需要滑动一下，才能数据页面才能正常显示。

经过查找发现，你在“## UIViewController+WXSTransition"中第176行添加了
### [_interactive_ addGestureToViewController:self];
覆盖了“## UINavigationController+FDFullscreenPopGesture”中的手势，导致无法作用，建议能否增加一个属性来控制是否添加这个手势，方便自定义呢。

**Comment by alanwangmodify** [comment]
感谢您的建议，现在已经加了，设置transition的 backGestureEnable 为NO,时就没有添加手势了。
