### ISSUE TITLE
转场动画下个界面如果是UITableViewController，会出现问题。

### ISSUE THREAD

**Issue by CultureCheng** [alanwangmodify/WXSTransition#5]
push会使tableview发生位移且不能滑动。
present会使tableview位移，状态栏全黑。

**Comment by KnivesCheung** [comment]
有个bug；导包进入时候，如果普通的转场动画，在第一次的时候都会用WXSTransitionAnimationTypeSysPushFromLeft这个样式，并且之后就会恢复系统默认动画样式。而且这个动画包很多的动画时间和tabbar消失，出现的时间不一致

**Comment by alanwangmodify** [comment]
TableView是因为自动布局的约束问题
