### ISSUE TITLE
不知道autolayout的环境下有什么好的转场动画效果库吗?

### ISSUE THREAD

**Issue by HellowjingQiu** [alanwangmodify/WXSTransition#6]
最近正在学习使用masonry实现auto的动画效果,发现纯代码的转场动画在转场的时候那一层的约束会丢失,我在想应该是view被取出然后又被放回的缘故导致约束链断裂,是否有一种方式可以记忆约束关系,为此取出和填回上下约束关系呢?(这是对一个实现库的猜想:P)

**Comment by alanwangmodify** [comment]
你可以试一下VCTransitionsLibrary
