### ISSUE TITLE
麻烦作者支持一下cocoapods

### ISSUE THREAD

**Issue by wyhazq** [alanwangmodify/WXSTransition#7]
如题

**Comment by wyhazq** [comment]
感觉动画稍微再快一点会更好

**Comment by alanwangmodify** [comment]
谢谢你的支持，但是现在WXSTransition还有很多未完善的地方，暂时不会加到cocoapods，我会尽快完善，然后加到cocoapods.
动画的时间可以自己定制，可以看一下readme相关使用方法。

**Comment by wjiuxing** [comment]
请问大概何时能支持cocoapods？谢谢

**Comment by alanwangmodify** [comment]
现在已经支持cocopods
